/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginWireframeRouteImport } from './routes/login-wireframe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRuanganIndexRouteImport } from './routes/_authenticated/ruangan/index'
import { Route as AuthenticatedPermintaanIndexRouteImport } from './routes/_authenticated/permintaan/index'
import { Route as AuthenticatedBarangIndexRouteImport } from './routes/_authenticated/barang/index'
import { Route as AuthenticatedPermintaanTambahRouteImport } from './routes/_authenticated/permintaan/tambah'
import { Route as AuthenticatedPengaturanKategoriRouteImport } from './routes/_authenticated/pengaturan/kategori'

const LoginWireframeRoute = LoginWireframeRouteImport.update({
  id: '/login-wireframe',
  path: '/login-wireframe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRuanganIndexRoute =
  AuthenticatedRuanganIndexRouteImport.update({
    id: '/ruangan/',
    path: '/ruangan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermintaanIndexRoute =
  AuthenticatedPermintaanIndexRouteImport.update({
    id: '/permintaan/',
    path: '/permintaan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBarangIndexRoute =
  AuthenticatedBarangIndexRouteImport.update({
    id: '/barang/',
    path: '/barang/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPermintaanTambahRoute =
  AuthenticatedPermintaanTambahRouteImport.update({
    id: '/permintaan/tambah',
    path: '/permintaan/tambah',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPengaturanKategoriRoute =
  AuthenticatedPengaturanKategoriRouteImport.update({
    id: '/pengaturan/kategori',
    path: '/pengaturan/kategori',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-wireframe': typeof LoginWireframeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/users': typeof AuthenticatedUsersRoute
  '/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/permintaan/tambah': typeof AuthenticatedPermintaanTambahRoute
  '/barang/': typeof AuthenticatedBarangIndexRoute
  '/permintaan/': typeof AuthenticatedPermintaanIndexRoute
  '/ruangan/': typeof AuthenticatedRuanganIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-wireframe': typeof LoginWireframeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/users': typeof AuthenticatedUsersRoute
  '/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/permintaan/tambah': typeof AuthenticatedPermintaanTambahRoute
  '/barang': typeof AuthenticatedBarangIndexRoute
  '/permintaan': typeof AuthenticatedPermintaanIndexRoute
  '/ruangan': typeof AuthenticatedRuanganIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/login-wireframe': typeof LoginWireframeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/pengaturan/kategori': typeof AuthenticatedPengaturanKategoriRoute
  '/_authenticated/permintaan/tambah': typeof AuthenticatedPermintaanTambahRoute
  '/_authenticated/barang/': typeof AuthenticatedBarangIndexRoute
  '/_authenticated/permintaan/': typeof AuthenticatedPermintaanIndexRoute
  '/_authenticated/ruangan/': typeof AuthenticatedRuanganIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-wireframe'
    | '/dashboard'
    | '/users'
    | '/pengaturan/kategori'
    | '/permintaan/tambah'
    | '/barang/'
    | '/permintaan/'
    | '/ruangan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-wireframe'
    | '/dashboard'
    | '/users'
    | '/pengaturan/kategori'
    | '/permintaan/tambah'
    | '/barang'
    | '/permintaan'
    | '/ruangan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/login-wireframe'
    | '/_authenticated/dashboard'
    | '/_authenticated/users'
    | '/_authenticated/pengaturan/kategori'
    | '/_authenticated/permintaan/tambah'
    | '/_authenticated/barang/'
    | '/_authenticated/permintaan/'
    | '/_authenticated/ruangan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginWireframeRoute: typeof LoginWireframeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-wireframe': {
      id: '/login-wireframe'
      path: '/login-wireframe'
      fullPath: '/login-wireframe'
      preLoaderRoute: typeof LoginWireframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ruangan/': {
      id: '/_authenticated/ruangan/'
      path: '/ruangan'
      fullPath: '/ruangan/'
      preLoaderRoute: typeof AuthenticatedRuanganIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permintaan/': {
      id: '/_authenticated/permintaan/'
      path: '/permintaan'
      fullPath: '/permintaan/'
      preLoaderRoute: typeof AuthenticatedPermintaanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/barang/': {
      id: '/_authenticated/barang/'
      path: '/barang'
      fullPath: '/barang/'
      preLoaderRoute: typeof AuthenticatedBarangIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/permintaan/tambah': {
      id: '/_authenticated/permintaan/tambah'
      path: '/permintaan/tambah'
      fullPath: '/permintaan/tambah'
      preLoaderRoute: typeof AuthenticatedPermintaanTambahRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pengaturan/kategori': {
      id: '/_authenticated/pengaturan/kategori'
      path: '/pengaturan/kategori'
      fullPath: '/pengaturan/kategori'
      preLoaderRoute: typeof AuthenticatedPengaturanKategoriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedPengaturanKategoriRoute: typeof AuthenticatedPengaturanKategoriRoute
  AuthenticatedPermintaanTambahRoute: typeof AuthenticatedPermintaanTambahRoute
  AuthenticatedBarangIndexRoute: typeof AuthenticatedBarangIndexRoute
  AuthenticatedPermintaanIndexRoute: typeof AuthenticatedPermintaanIndexRoute
  AuthenticatedRuanganIndexRoute: typeof AuthenticatedRuanganIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedPengaturanKategoriRoute: AuthenticatedPengaturanKategoriRoute,
  AuthenticatedPermintaanTambahRoute: AuthenticatedPermintaanTambahRoute,
  AuthenticatedBarangIndexRoute: AuthenticatedBarangIndexRoute,
  AuthenticatedPermintaanIndexRoute: AuthenticatedPermintaanIndexRoute,
  AuthenticatedRuanganIndexRoute: AuthenticatedRuanganIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginWireframeRoute: LoginWireframeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
